import fs from 'fs';
import path from 'path';

/**
 * Stub PDF generator - creates a simple text-based report
 * Will be replaced with actual Markdown -> PDF conversion later
 */
export async function generateReportPDF(specimenData, gradingResult, outputPath) {
  console.log(`📄 Generating PDF report (stub) for ${specimenData.id}`);
  
  const reportContent = generateReportContent(specimenData, gradingResult);
  
  // Ensure output directory exists
  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  
  // For now, write a text file (will be replaced with actual PDF)
  const textPath = outputPath.replace('.pdf', '.txt');
  fs.writeFileSync(textPath, reportContent, 'utf8');
  
  // Create a placeholder PDF marker
  fs.writeFileSync(outputPath, `PDF_PLACEHOLDER: ${specimenData.id}\n${reportContent}`, 'utf8');
  
  console.log(`✅ Report generated at: ${outputPath}`);
  return outputPath;
}

function generateReportContent(specimen, grading) {
  const divider = '='.repeat(80);
  
  return `
${divider}
MULTIVIEW CTC GRADING REPORT
${divider}

HEADER / IDENTIFICATION
───────────────────────────────────────────────────────────────────────────────
Specimen ID:        ${specimen.id}
Certification ID:   ${specimen.certification_id}
Classification:     ${specimen.classification} (${specimen.classification === 'MV' ? 'Measurement-Verified' : 'Visual-Only'})
${specimen.box_id ? `Box ID:             ${specimen.box_id}\n` : ''}Framework:          Multiview Grading Standards ${grading.frameworkVersion}
Date Graded:        ${new Date(specimen.date_iso).toLocaleString()}

${divider}
FINAL GRADE
${divider}

${grading.grade}

${divider}
SUBGRADE BREAKDOWN
${divider}

Geometry:           ${grading.subgrades.geometry.toFixed(1)} / 10.0
Corners:            ${grading.subgrades.corners.toFixed(1)} / 10.0
Coating:            ${grading.subgrades.coating.toFixed(1)} / 10.0
Surface:            ${grading.subgrades.surface.toFixed(1)} / 10.0
Alignment:          ${grading.subgrades.alignment.toFixed(1)} / 10.0

${divider}
${specimen.classification === 'MV' ? 'MEASUREMENTS (Verified)' : 'VISUAL ANALYSIS'}
${divider}

${specimen.classification === 'MV' ? `
Weight:             ${specimen.weight_g ? specimen.weight_g + ' g' : 'Not provided'}
Height:             ${specimen.height_mm ? specimen.height_mm + ' mm' : 'Not provided'}
Width:              ${specimen.width_mm ? specimen.width_mm + ' mm' : 'Not provided'}
Depth:              ${specimen.depth_mm ? specimen.depth_mm + ' mm' : 'Not provided'}
` : `
Analysis based on photographic evidence only.
No physical measurements provided.
`}

${divider}
GRADING NOTES
${divider}

${grading.notes}

${divider}
TECHNICAL DETAILS
${divider}

${Object.entries(grading.technicalDetails).map(([key, value]) => 
  `${key.replace(/([A-Z])/g, ' $1').trim()}:`.padEnd(25) + value
).join('\n')}

${specimen.notes ? `\n${divider}\nSUBMITTER NOTES\n${divider}\n\n${specimen.notes}\n` : ''}

${divider}
PHOTOS
${divider}

Total Images: ${specimen.photos_json ? JSON.parse(specimen.photos_json).length : 0}
${specimen.photos_json ? JSON.parse(specimen.photos_json).map((p, i) => `  ${i + 1}. ${p}`).join('\n') : ''}

${divider}
SYSTEM & PROVENANCE
${divider}

Cataloged by:       Shawn Wiederhoeft
System:             Multiview CTC Grader v2.0
Database:           SQLite (local)
Report Generated:   ${new Date().toISOString()}

${divider}

Multiview Technology © 2025
This report is generated by an automated grading system.
${specimen.classification === 'MV' ? 'Physical measurements verified.' : 'Visual-only analysis.'}

${divider}
`;
}

